<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_master by id
     */
    
    public function get_all_hobbies($user_id)
    {
        $query = $this->db->select('*')
                          ->from('user_table')
                          ->join('hobby','hobby.user_id=user_table.user_id','left')
                          ->join('sub_hobby','sub_hobby.hobby_id=hobby.hobby_id','left')
                          ->where('user_table.user_id',$user_id)
                          ->get();
        return $query->result();
    }

    public function get_hobbies($user_id)
    {
        $query = $this->db->select('*')
                          ->from('hobby')
                          ->where('user_id',$user_id)
                          ->get();
        return $query->result();
    }

    public function save_hobby($array)
    {
        $this->db->insert('hobby',$array);
    }

    public function update_hobby($array,$id)
    {
        $this->db->where('hobby_id',$id)
                 ->update('hobby',$array);
    }

    public function delete_hobby($id)
    {
        $this->db->where('hobby_id',$id)
                 ->delete('hobby');
    }

    public function get_subhobbies($user_id)
    {
        $query = $this->db->select('*')
                          ->from('sub_hobby')
                          ->join('hobby','hobby.hobby_id=sub_hobby.hobby_id','left')
                          ->where('hobby.user_id',$user_id)
                          ->get();
        return $query->result();
    }

    public function insert_subhobby($array)
    {
        $this->db->insert('sub_hobby',$array);
    }

    public function update_sub_hobby($array,$id)
    {
        $this->db->where('sub_hobby_id',$id)
                 ->update('sub_hobby',$array);
    }

    public function delete_sub_hobby($id)
    {
        $this->db->where('sub_hobby_id',$id)
                 ->delete('sub_hobby');
    }
}
